on:
  push:
    branches:
      - main
  pull_request:

name: Coveralls

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        uses: actions/checkout@v3
      - name: Install modules
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run tests
        run: yarn test --coverage
      - name: Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
